version: '3'
services:
  web_app:
    build: 
      context: ./web_app
      dockerfile: ./Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - backend_api
    environment:
      FLASK_APP: web_app/app.py
    env_file:
      - .env

  backend_api:
    build:
      context: ./backend_api
      dockerfile: ./Dockerfile
    ports:
      - "5002:5002"
    environment:
      FLASK_APP: backend_api/google_api.py
    env_file:
      - .env
